spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/supplyx
    username: supplyx
    password: supplyx
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  test:
    database:
      replace: none

logging:
  level:
    root: INFO
  file:
    name: logs/test.log
